
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  passwordHash: 'passwordHash',
  fullName: 'fullName',
  email: 'email',
  phone: 'phone',
  isActive: 'isActive',
  lastLoginAt: 'lastLoginAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  doctorId: 'doctorId'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
};

exports.Prisma.PermissionScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  category: 'category',
  description: 'description'
};

exports.Prisma.UserRoleScalarFieldEnum = {
  userId: 'userId',
  roleId: 'roleId'
};

exports.Prisma.RolePermissionScalarFieldEnum = {
  roleId: 'roleId',
  permissionId: 'permissionId'
};

exports.Prisma.PanelClientScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  contactPerson: 'contactPerson',
  phone: 'phone',
  email: 'email',
  address: 'address',
  discountPercent: 'discountPercent',
  billingType: 'billingType',
  effectiveStartDate: 'effectiveStartDate',
  effectiveEndDate: 'effectiveEndDate',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PatientScalarFieldEnum = {
  id: 'id',
  mrn: 'mrn',
  fullName: 'fullName',
  guardianName: 'guardianName',
  dob: 'dob',
  age: 'age',
  gender: 'gender',
  bloodGroup: 'bloodGroup',
  phone: 'phone',
  alternatePhone: 'alternatePhone',
  address: 'address',
  city: 'city',
  nic: 'nic',
  employeeId: 'employeeId',
  panelClientId: 'panelClientId',
  emergencyContactName: 'emergencyContactName',
  emergencyContactPhone: 'emergencyContactPhone',
  emergencyContactRelation: 'emergencyContactRelation',
  registrationDate: 'registrationDate',
  isActive: 'isActive',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DepartmentScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  description: 'description',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DoctorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  printableTitle: 'printableTitle',
  licenseNumber: 'licenseNumber',
  specialty: 'specialty',
  phone: 'phone',
  email: 'email',
  departmentId: 'departmentId',
  consultationFee: 'consultationFee',
  followUpFee: 'followUpFee',
  signatureData: 'signatureData',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VisitScalarFieldEnum = {
  id: 'id',
  visitNumber: 'visitNumber',
  patientId: 'patientId',
  doctorId: 'doctorId',
  departmentId: 'departmentId',
  visitDateTime: 'visitDateTime',
  tokenNumber: 'tokenNumber',
  visitType: 'visitType',
  status: 'status',
  paymentStatus: 'paymentStatus',
  priority: 'priority',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VisitVitalsScalarFieldEnum = {
  id: 'id',
  visitId: 'visitId',
  patientId: 'patientId',
  temperature: 'temperature',
  pulse: 'pulse',
  respiratoryRate: 'respiratoryRate',
  systolicBp: 'systolicBp',
  diastolicBp: 'diastolicBp',
  spo2: 'spo2',
  weight: 'weight',
  height: 'height',
  bmi: 'bmi',
  bloodGlucose: 'bloodGlucose',
  glucoseType: 'glucoseType',
  painScore: 'painScore',
  observations: 'observations',
  recordedById: 'recordedById',
  recordedAt: 'recordedAt'
};

exports.Prisma.ConsultationScalarFieldEnum = {
  id: 'id',
  visitId: 'visitId',
  patientId: 'patientId',
  doctorId: 'doctorId',
  chiefComplaint: 'chiefComplaint',
  historyOfPresentIllness: 'historyOfPresentIllness',
  pastMedicalHistory: 'pastMedicalHistory',
  physicalExamination: 'physicalExamination',
  diagnosis: 'diagnosis',
  clinicalNotes: 'clinicalNotes',
  advice: 'advice',
  followUpDate: 'followUpDate',
  status: 'status',
  finalizedAt: 'finalizedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ConsultationAmendmentScalarFieldEnum = {
  id: 'id',
  consultationId: 'consultationId',
  amendedById: 'amendedById',
  amendedAt: 'amendedAt',
  reason: 'reason',
  previousContent: 'previousContent',
  newContent: 'newContent'
};

exports.Prisma.MedicineScalarFieldEnum = {
  id: 'id',
  brandName: 'brandName',
  genericName: 'genericName',
  strength: 'strength',
  dosageForm: 'dosageForm',
  manufacturer: 'manufacturer',
  defaultDosage: 'defaultDosage',
  defaultFrequency: 'defaultFrequency',
  defaultRoute: 'defaultRoute',
  defaultDuration: 'defaultDuration',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvestigationScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  category: 'category',
  description: 'description',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PrescriptionScalarFieldEnum = {
  id: 'id',
  prescriptionNo: 'prescriptionNo',
  visitId: 'visitId',
  patientId: 'patientId',
  doctorId: 'doctorId',
  consultationId: 'consultationId',
  diagnosis: 'diagnosis',
  clinicalNotes: 'clinicalNotes',
  advice: 'advice',
  followUpDate: 'followUpDate',
  status: 'status',
  finalizedAt: 'finalizedAt',
  version: 'version',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PrescriptionItemScalarFieldEnum = {
  id: 'id',
  prescriptionId: 'prescriptionId',
  medicineId: 'medicineId',
  medicineName: 'medicineName',
  genericName: 'genericName',
  strength: 'strength',
  dosageForm: 'dosageForm',
  dose: 'dose',
  frequency: 'frequency',
  route: 'route',
  duration: 'duration',
  quantity: 'quantity',
  instructions: 'instructions',
  foodRelation: 'foodRelation',
  additionalNotes: 'additionalNotes',
  sortOrder: 'sortOrder'
};

exports.Prisma.PrescriptionInvestigationScalarFieldEnum = {
  id: 'id',
  prescriptionId: 'prescriptionId',
  investigationId: 'investigationId',
  investigationName: 'investigationName',
  instructions: 'instructions',
  sortOrder: 'sortOrder'
};

exports.Prisma.PrescriptionAmendmentScalarFieldEnum = {
  id: 'id',
  prescriptionId: 'prescriptionId',
  amendedById: 'amendedById',
  amendedAt: 'amendedAt',
  reason: 'reason',
  previousContent: 'previousContent',
  newContent: 'newContent'
};

exports.Prisma.ServiceScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  category: 'category',
  standardPrice: 'standardPrice',
  isTaxable: 'isTaxable',
  taxPercent: 'taxPercent',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ServicePriceScalarFieldEnum = {
  id: 'id',
  serviceId: 'serviceId',
  departmentId: 'departmentId',
  doctorId: 'doctorId',
  panelClientId: 'panelClientId',
  price: 'price',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VisitChargeScalarFieldEnum = {
  id: 'id',
  visitId: 'visitId',
  patientId: 'patientId',
  serviceId: 'serviceId',
  serviceName: 'serviceName',
  description: 'description',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  discount: 'discount',
  taxAmount: 'taxAmount',
  netAmount: 'netAmount',
  status: 'status',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  invoiceNumber: 'invoiceNumber',
  visitId: 'visitId',
  patientId: 'patientId',
  doctorId: 'doctorId',
  panelClientId: 'panelClientId',
  subtotal: 'subtotal',
  discountTotal: 'discountTotal',
  taxTotal: 'taxTotal',
  netTotal: 'netTotal',
  paidTotal: 'paidTotal',
  balanceTotal: 'balanceTotal',
  status: 'status',
  panelClaimNo: 'panelClaimNo',
  notes: 'notes',
  createdById: 'createdById',
  createdAt: 'createdAt',
  finalizedAt: 'finalizedAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceItemScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  chargeId: 'chargeId',
  serviceName: 'serviceName',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  discount: 'discount',
  taxAmount: 'taxAmount',
  netAmount: 'netAmount',
  createdAt: 'createdAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  receiptNumber: 'receiptNumber',
  invoiceId: 'invoiceId',
  patientId: 'patientId',
  amount: 'amount',
  paymentMethod: 'paymentMethod',
  transactionReference: 'transactionReference',
  notes: 'notes',
  receivedById: 'receivedById',
  receivedAt: 'receivedAt'
};

exports.Prisma.FinancialAdjustmentScalarFieldEnum = {
  id: 'id',
  adjustmentNumber: 'adjustmentNumber',
  invoiceId: 'invoiceId',
  paymentId: 'paymentId',
  type: 'type',
  originalAmount: 'originalAmount',
  adjustedAmount: 'adjustedAmount',
  differenceAmount: 'differenceAmount',
  reason: 'reason',
  authorizedById: 'authorizedById',
  createdAt: 'createdAt'
};

exports.Prisma.SequenceCounterScalarFieldEnum = {
  name: 'name',
  prefix: 'prefix',
  currentVal: 'currentVal',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  userName: 'userName',
  userRole: 'userRole',
  action: 'action',
  entityType: 'entityType',
  entityId: 'entityId',
  oldValue: 'oldValue',
  newValue: 'newValue',
  reason: 'reason',
  ipAddress: 'ipAddress',
  timestamp: 'timestamp'
};

exports.Prisma.HospitalSettingScalarFieldEnum = {
  id: 'id',
  hospitalName: 'hospitalName',
  tagline: 'tagline',
  address: 'address',
  city: 'city',
  phone: 'phone',
  email: 'email',
  website: 'website',
  taxNumber: 'taxNumber',
  currencySymbol: 'currencySymbol',
  logoBase64: 'logoBase64',
  prescriptionDisclaimer: 'prescriptionDisclaimer',
  invoiceDisclaimer: 'invoiceDisclaimer',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.RoleType = exports.$Enums.RoleType = {
  ADMINISTRATOR: 'ADMINISTRATOR',
  RECEPTION: 'RECEPTION',
  NURSE: 'NURSE',
  DOCTOR: 'DOCTOR',
  CASHIER: 'CASHIER',
  HOSPITAL_MANAGER: 'HOSPITAL_MANAGER'
};

exports.Gender = exports.$Enums.Gender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER'
};

exports.BloodGroup = exports.$Enums.BloodGroup = {
  A_POSITIVE: 'A_POSITIVE',
  A_NEGATIVE: 'A_NEGATIVE',
  B_POSITIVE: 'B_POSITIVE',
  B_NEGATIVE: 'B_NEGATIVE',
  AB_POSITIVE: 'AB_POSITIVE',
  AB_NEGATIVE: 'AB_NEGATIVE',
  O_POSITIVE: 'O_POSITIVE',
  O_NEGATIVE: 'O_NEGATIVE',
  UNKNOWN: 'UNKNOWN'
};

exports.VisitType = exports.$Enums.VisitType = {
  NEW_CONSULTATION: 'NEW_CONSULTATION',
  FOLLOW_UP: 'FOLLOW_UP',
  EMERGENCY: 'EMERGENCY',
  OTHER: 'OTHER'
};

exports.VisitStatus = exports.$Enums.VisitStatus = {
  REGISTERED: 'REGISTERED',
  WAITING: 'WAITING',
  VITALS_COMPLETED: 'VITALS_COMPLETED',
  WITH_DOCTOR: 'WITH_DOCTOR',
  CONSULTATION_COMPLETED: 'CONSULTATION_COMPLETED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

exports.VisitPaymentStatus = exports.$Enums.VisitPaymentStatus = {
  UNBILLED: 'UNBILLED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  CREDIT_PANEL: 'CREDIT_PANEL',
  VOID: 'VOID'
};

exports.ClinicalRecordStatus = exports.$Enums.ClinicalRecordStatus = {
  DRAFT: 'DRAFT',
  FINALIZED: 'FINALIZED',
  AMENDED: 'AMENDED'
};

exports.FoodRelation = exports.$Enums.FoodRelation = {
  BEFORE_FOOD: 'BEFORE_FOOD',
  AFTER_FOOD: 'AFTER_FOOD',
  WITH_FOOD: 'WITH_FOOD',
  EMPTY_STOMACH: 'EMPTY_STOMACH',
  NO_RESTRICTION: 'NO_RESTRICTION'
};

exports.ServiceCategory = exports.$Enums.ServiceCategory = {
  CONSULTATION: 'CONSULTATION',
  FOLLOW_UP: 'FOLLOW_UP',
  REGISTRATION: 'REGISTRATION',
  PROCEDURE: 'PROCEDURE',
  NURSING: 'NURSING',
  DRESSING: 'DRESSING',
  OTHER: 'OTHER'
};

exports.ChargeStatus = exports.$Enums.ChargeStatus = {
  DRAFT: 'DRAFT',
  FINALIZED: 'FINALIZED',
  BILLED: 'BILLED',
  VOIDED: 'VOIDED',
  ADJUSTED: 'ADJUSTED'
};

exports.InvoiceStatus = exports.$Enums.InvoiceStatus = {
  DRAFT: 'DRAFT',
  FINALIZED: 'FINALIZED',
  PAID: 'PAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  VOIDED: 'VOIDED',
  ADJUSTED: 'ADJUSTED',
  REFUNDED: 'REFUNDED'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  CASH: 'CASH',
  CARD: 'CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  PANEL_CREDIT: 'PANEL_CREDIT',
  CHEQUE: 'CHEQUE',
  ONLINE: 'ONLINE'
};

exports.AdjustmentType = exports.$Enums.AdjustmentType = {
  DISCOUNT_ADJUSTMENT: 'DISCOUNT_ADJUSTMENT',
  CORRECTION: 'CORRECTION',
  REFUND: 'REFUND',
  WRITE_OFF: 'WRITE_OFF',
  VOID: 'VOID'
};

exports.Prisma.ModelName = {
  User: 'User',
  Role: 'Role',
  Permission: 'Permission',
  UserRole: 'UserRole',
  RolePermission: 'RolePermission',
  PanelClient: 'PanelClient',
  Patient: 'Patient',
  Department: 'Department',
  Doctor: 'Doctor',
  Visit: 'Visit',
  VisitVitals: 'VisitVitals',
  Consultation: 'Consultation',
  ConsultationAmendment: 'ConsultationAmendment',
  Medicine: 'Medicine',
  Investigation: 'Investigation',
  Prescription: 'Prescription',
  PrescriptionItem: 'PrescriptionItem',
  PrescriptionInvestigation: 'PrescriptionInvestigation',
  PrescriptionAmendment: 'PrescriptionAmendment',
  Service: 'Service',
  ServicePrice: 'ServicePrice',
  VisitCharge: 'VisitCharge',
  Invoice: 'Invoice',
  InvoiceItem: 'InvoiceItem',
  Payment: 'Payment',
  FinancialAdjustment: 'FinancialAdjustment',
  SequenceCounter: 'SequenceCounter',
  AuditLog: 'AuditLog',
  HospitalSetting: 'HospitalSetting'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
