export enum RoleType {
  ADMINISTRATOR = 'ADMINISTRATOR',
  RECEPTION = 'RECEPTION',
}

export const ROLE_PERMISSIONS: Record<RoleType, string[]> = {
  [RoleType.ADMINISTRATOR]: [
    'patient:create',
    'patient:read',
    'patient:update_demographics',
    'patient:view_full_history',
    'visit:create',
    'visit:read',
    'visit:update_status',
    'visit:cancel',
    'vitals:record',
    'vitals:read',
    'consultation:create',
    'consultation:read',
    'consultation:amend',
    'prescription:create',
    'prescription:finalize',
    'prescription:amend',
    'prescription:print',
    'billing:create_charge',
    'billing:create_invoice',
    'billing:receive_payment',
    'billing:apply_discount',
    'billing:adjust_financial',
    'billing:void_invoice',
    'billing:print_slip',
    'report:view_operational',
    'report:view_financial',
    'report:export',
    'admin:manage_users',
    'admin:manage_masters',
    'admin:audit_logs',
    'admin:backup_restore',
  ],
  [RoleType.RECEPTION]: [
    'patient:create',
    'patient:read',
    'patient:update_demographics',
    'patient:view_full_history',
    'visit:create',
    'visit:read',
    'visit:update_status',
    'visit:cancel',
    'vitals:record',
    'vitals:read',
    'consultation:read',
    'prescription:print',
    'billing:create_charge',
    'billing:create_invoice',
    'billing:receive_payment',
    'billing:apply_discount',
    'billing:print_slip',
    'report:view_operational',
  ],
};
